### PR TITLE
Update nrpe.cfg

### PR DESCRIPTION
**Pull request by sean-m-sullivan**
Host is no longer working, updated it to inventory_hostname on line 24 and 27 so it runs correctly.

### CODE REVIEW

**Comment by sdarwin** [comment]
Hi Sean,
Nice to hear from you!
So, let's consider these lines of code in the file.

23 {% for host in groups[nagios_monitoring_servers_group_name] %}
24 {% for ip in hostvars[host]['ansible_all_ipv4_addresses'] %}

"host" is just a variable here. It could as well be "x":

23 {% for x in groups[nagios_monitoring_servers_group_name] %}
24 {% for ip in hostvars[x]['ansible_all_ipv4_addresses'] %}

While you are comparing or contrasting hostvars[inventory_hostname] and hostvars[host], in this particular context inventory_hostname may not even be set.  How about adding these debugging statements after line 23 in the template:

the variable inventory_hostname is set to {{ inventory_hostname }}
the variable host is set to {{ host }}

What does it print in the template after that?

**Comment by sdarwin** [comment]
An explanation for the problem could be that monitoring servers are not set? I have just updated the README to clarify further.

Add nagios servers to the monitoring-servers group in the Ansible inventory. Example:

[monitoring-servers]
monitor.example.com

**Comment by sean-m-sullivan** [comment]
Maybe its that I'm using an older version of ansible(2.4.3) due to a program requirement elsewhere, but even when changing it, i still get the error. 
Sample inventory Version 1:
```
[clients]
172.16.0.2

[monitoring-servers]
tester-1
```
Version 2:
```
[clients]
172.16.0.2

[monitoring-servers]
172.16.0.3

```
Using [host] I get the following error: 
```
fatal: [172.16.0.2]: FAILED! => {
    "changed": false, 
    "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'ansible_all_ipv4_addresses'"
}
```
versus if I use [inventory_hostname] the error doesn't occur if I use either the Ip address in the inventory or the resolving name.

**Comment by sdarwin** [comment]
That is interesting.  When I have a chance I will test out what you are mentioning, which is having IP addresses in the inventory.  Usually I put hostnames not IP's.   Still, ideally they would be supported and not crash Ansible.

The problem with inventory_hostname, is that it's a single value. The inventory_hostname.  However, in that place in the template we are trying to loop over many hosts, all the hosts, and the looping variable happens to be "hosts", although it could be "x", or "y", some other name.  The important thing, is that it's a for loop, and iterates over multiple values.   inventory_hostname will just be the same each time.

**Comment by sdarwin** [comment]
Have you modified nagios_monitoring_servers_group_name ? It should stay as the default value. The error indicates that as a possible issue.
 
I just tested ansible 2.4.1.0 and  2.6.0 on Ubuntu 16.  Both IP and hostname inventory.  So far no error there.

**Comment by sdarwin** [comment]
Any news?
If the problem is still occurring, please add this debugging section to the template right after line 23, and then post the resulting output here, or send it to me.

the variable inventory_hostname is set to {{ inventory_hostname }}
the variable host is set to {{ host }}
the variable nagios_monitoring_servers_group_name is set to {{ nagios_monitoring_servers_group_name }}

And, you might try setting up a new Ansible control machine with the very latest version of Ansible, just for Nagios.  What happens with the newest Ansible directly from github?
And, what OS version are the clients and the servers? Is it an old operating system?

**Comment by sdarwin** [comment]
> "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'ansible_all_ipv4_addresses'"

When setting up travis-ci, I encountered this very error. The problem was that docker instances don't have the iproute2 package installed, and it's required to retrieve 'ansible_all_ipv4_addresses'. A solution was to install the required packages and then collect the variables with setup again. Add a pre_task:

```
- hosts: all
  pre_tasks:
    - name: Install dependencies
      apt:
        name: 
          - iproute2
      when: ansible_os_family == 'Debian'

    - name: re-gather facts 
      setup:
```

**Comment by sdarwin** [comment]
closing issue due to inactivity.  can be re-opened later if needed.

**Pull request closed without merging**
