### PR TITLE
Change nagios_plugin_packages to match Debian-family.yml

### PR DESCRIPTION
**Pull request by misilot**
Change nagios_plugin_packages to default_nagios_plugin_packages which is the value in vars/Debian-family.yml

The value nagios_plugin_packages does not exist and will fail since the variable does not exist.

### CODE REVIEW

**Comment by sdarwin** [comment]
Hi Thomas,
Thanks for the feedback! It brings up an interesting point. 
Are you running this Role in the same way as shown in Ansible-Nagios/default.yml , which is like this, more or less:
roles:
        - { role: 'sdarwin.nagios', run_nagios_client: true }
etc etc.
Or are you, in some customized way, directly calling server.yml and client.yml? Are you bypassing main.yml?
The reason for the question is that main.yml (which is usually called when running the Role) does variable parsing, and it already fixes the issue.

**Comment by misilot** [comment]
I am doing it as a task

```
  vars:
    - run_nagios_server: true
    - run_nagios_client: true
    - nagios_monitoring_servers_group_name: tag_nagioshost_yes

  tasks:
    - include_role:
        name: sdarwin.nagios                            
```

**Comment by sdarwin** [comment]
Can you please provide this info:
- Version of Ansible
- Version of Operating System
- Error message which was appearing?

the role has a .kitchen.yml and .travis.yml, it was tested with Travis-CI and Test Kitchen, and was building successfully. 
However, the new pull request is not building in Travis.

Could you provide a reproducible test case, where I could try it out, and see the bug?
I have just tested something: adding the task code you posted in your previous message into the Ansible-Nagios/default.yml playbook.  (But otherwise without the new pull request.) Ran Test Kitchen again. The result of was: ok=67   changed=43   unreachable=0    failed=0   .

**Comment by sdarwin** [comment]
closing issue due to inactivity.  can be re-opened later if needed.

**Pull request closed without merging**
