### PR TITLE
Adding variable for customizing ansible inventory group name

### PR DESCRIPTION
**Pull request by zkupu**
My organization has a substantial ansible inventory and the existing group name in this role (monitoring-servers) is already in use elsewhere and can not be changed. 

I needed to be able to customize this, and I am sure that others would like to customize it as well. 

I've added in the variable to defaults/main.yml and updated the README to reflect the change as well!

### CODE REVIEW

**Comment by sdarwin** [comment]
Hi Zachary,

Those look like good features.
Some feedback:
1. In order to support both Redhat and Ubuntu, the nagios.conf template file destination should be variabilized, rather than hard-coded,  Destination "{{ nagios_with_httpd_conf }}/nagios.conf" . 
2. nagios.conf is a template, why not templatize it? That is to say, the web auth logic is choosing between "AuthType basic" and "AuthType none".  That could be an "if" statement inside the template. Then, install the file every time, not conditionally.  
3. Add documentation with the new variable in defaults/main.yml :
```
#This should match your top-level ansible playbook, such as "- hosts: monitoring-servers" 
nagios_monitoring_servers_group_name: "monitoring-servers"
```

**Comment by zkupu** [comment]
Hey there! Thank you for reviewing my pull requests! :D 

I really appreciate the feedback and fully agree. This was a simple change I put in place for my specific use case and as I iterate over my changes, I will incorporate your recommendations to make this usable in different circumstances. 

I'll submit another pull request once I have made the changes you suggested.

Thanks again!

P.S. This was my very first pull request ever. Thanks for being so quick to respond!! :D :D

**Comment by sdarwin** [comment]
Probably what happened was you submitted the pull request with one feature, and then github automatically included every commit afterwards.  Now this pull request has your entire master branch. The general solution is to use a feature branch instead: http://blog.jasonmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/

**Comment by zkupu** [comment]
Ahh, ok. I will re-submit the pull request from a feature branch so that my work isn't polluting our work. :D

**Pull request closed without merging**
